### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by Falghere** [despa1r1337/reportbot#2]
Instead of using multiple folders with 11 accounts in each of them ....

do something inside the script where we can choose the quantity, example:

I have 1k accounts

but I just want to send 20 reports so it could be

steamid64 20 matchid

you can see codes like this looking in unknowcheats search for sirystes they have codes like this fully open

**Comment by verdammnis** [comment]
> Instead of using multiple folders with 11 accounts in each of them ....
> 
> do something inside the script where we can choose the quantity, example:
> 
> I have 1k accounts
> 
> but I just want to send 20 reports so it could be
> 
> steamid64 20 matchid
> 
> you can see codes like this looking in unknowcheats search for sirystes they have codes like this fully open

you have to do it yourself. When I get bored, I might do it

**Comment by Falghere** [comment]
I don't have all this knowledge ... but this is not even that important despite being quite useful ...

something more useful than that would be if reports did the same as commends do ... connect to the starting server and then report
because by normal reporting methods it seems that it is no longer functional

**Comment by verdammnis** [comment]
> I don't have all this knowledge ... but this is not even that important despite being quite useful ...
> 
> something more useful than that would be if reports did the same as commends do ... connect to the starting server and then report
> because by normal reporting methods it seems that it is no longer functional


if your ReportBot fixed, that's why you get the answer?) If the report system was fixed, then it would get stuck on the GC connection and eventually get the error. But you get the answer, isn't it strange? if commendbot was really fixed, the old method has stuck on connecting GC, not here. we conclude: ReportBot - works. cheaters are lucky, because the patrol no one is watching, remember 2016,2017 YouTube was overflowing with rubrics ( inspection patrol), the consequence of which, a cheater, it was impossible to survive, but right now? All was quiet, the hype is gone. People don't watch patrol, because it's not a reward, might give: cases, weapons. But they give nothing.


sorry if there are mistakes somewhere, my English is bad

**Comment by verdammnis** [comment]
you used ReportBot, which is made by another method, perhaps an old. I have another method, there is no need Steam API key. Everything happens through the client system
